### ISSUE TITLE
Custom motd

### ISSUE THREAD

**Issue by stuart-warren** [coreos/init#149]
Are you open to the idea of loading in a custom textfile (if it exists) to /run/coreos/motd during the motdgen service?
https://github.com/coreos/init/blob/master/scripts/motdgen

```
###################################################################
# This system is for the use of authorized users only.            #
# Individuals using this computer system without authority, or in #
blah blah blah
```

If so, where would you prefer it pick it up from?
We can then write that textfile in our cloud-init.

**Comment by marineam** [comment]
Hm, I'm thinking either match debian and use `/etc/motd.tail` or match most everything else and accept a directory of any number of extras like `/etc/motd.d/foo.conf`

Either is fine with me, but I'm leaning towards the latter.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/init/pull/150.
